open-orchestra/open-orchestra-model-bundle

- ModelBundle/Document/ContentType.php
Belongs to a pool of 3 PR :
open-orchestra-cms-bundle, open-orchestra-model-bundle, open-orchestra-model-interface
> Add edit form custom template for content

- ModelBundle/DataFixtures/MongoDB/LoadContentData.php
- ModelBundle/DataFixtures/MongoDB/LoadContentTypeData.php
- ModelBundle/Repository/ContentTypeRepository.php
- ModelBundle/Tests/Functional/Repository/ContentTypeRepositoryTest.php
3 PR concomitantes :
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/702
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/283
https://github.com/open-orchestra/open-orchestra-model-interface/pull/53
> Add findOneByContentTypeInLastVersion

- ModelBundle/DataFixtures/MongoDB/LoadContentTypeData.php
- ModelBundle/Document/ContentType.php
- ModelBundle/Tests/Functional/Model/EntityTest.php
https://github.com/open-orchestra/open-orchestra-model-interface/pull/52
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/701
> delete status of contentType

- ModelBundle/DataFixtures/MongoDB/LoadNodeData.php
- ModelBundle/DataFixtures/MongoDB/LoadNodeDemoData.php
- ModelBundle/Manager/NodeManager.php
- ModelBundle/Tests/Manager/NodeManagerTest.php
https://github.com/open-orchestra/open-orchestra-model-interface/pull/66
> change const name

- ModelBundle/Document/FieldType.php
in relation with https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/768
> initialize options when clone fieldType

- ModelBundle/Repository/ContentRepository.php
https://trello.com/c/cRlKESMj/973-refacto-remplacer-le-foreach-de-contentrepository-findlastversion-par-un-aggregat
> Refacto aggregate for Content List Bloc

- ModelBundle/Document/Site.php
https://github.com/open-orchestra/open-orchestra-front-bundle/pull/95
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/318
https://github.com/open-orchestra/open-orchestra-model-interface/pull/70
> Add getMainAlaisId() for https://github.com/open-orchestra/open-orchestra-front-bundle/pull/95

- ModelBundle/Document/ContentType.php
- ModelBundle/Repository/ContentTypeRepository.php
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/322
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/807
> Mongo index translatedvalues by language

- ModelBundle/Resources/config/validation.yml
Seems to pass the functionnal tests now, so there's no reason to keep it commented
> Reactivate PreventPublishedDocumentSave validator

- ModelBundle/EventListener/GenerateIdListener.php
- ModelBundle/Repository/ContentRepository.php
- ModelBundle/Repository/NodeRepository.php
- ModelBundle/Repository/TemplateRepository.php
- ModelBundle/Tests/EventListener/GenerateIdListenerTest.php
- ModelBundle/Tests/Functional/Repository/ContentRepositoryTest.php
fix issue https://github.com/open-orchestra/open-orchestra-model-interface/issues/60
> rename testUnicityInContext by testUniquenessInContext

- ModelBundle/DependencyInjection/OpenOrchestraModelExtension.php
https://github.com/open-orchestra/open-orchestra-base-api-bundle/pull/18
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/844
https://github.com/open-orchestra/open-orchestra-media-bundle/pull/55
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/333
https://github.com/open-orchestra/open-orchestra-workflow-function-bundle/pull/9
> Replace deprecated method definition->setFactory*

- ModelBundle/Form/DataTransformer/EmbedSiteToSiteTransformer.php
- ModelBundle/Form/Type/OrchestraSiteType.php
- ModelBundle/Resources/config/form.yml
- ModelBundle/Resources/config/transformer.yml
- ModelBundle/Tests/Form/DataTransformer/EmbedSiteToSiteTransformerTest.php
- ModelBundle/Tests/Form/Type/OrchestraSiteTypeTest.php
> fix folder save

- ModelBundle/DataFixtures/MongoDB/LoadNodeDemoData.php
- ModelBundle/DataFixtures/MongoDB/LoadSiteData.php
- ModelBundle/Document/Site.php
- ModelBundle/Tests/Document/SiteTest.php
- ModelBundle/Tests/Functional/Repository/NodeRepositoryTest.php
https://github.com/open-orchestra/open-orchestra-display-bundle/pull/152
https://github.com/open-orchestra/open-orchestra-model-interface/pull/79
https://github.com/open-orchestra/open-orchestra-front-bundle/pull/97
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/340
> implement method

- ModelBundle/Repository/ContentRepository.php
- ModelBundle/Repository/ContentTypeRepository.php
- ModelBundle/Repository/RepositoryTrait/PaginateAndSearchFilterTrait.php
- ModelBundle/Repository/SiteRepository.php
- ModelBundle/Tests/Functional/Repository/ContentRepositoryTest.php
- ModelBundle/Tests/Functional/Repository/SiteRepositoryTest.php
https://github.com/open-orchestra/open-orchestra-model-interface/pull/80
> Use finder configuration

- ModelBundle/Repository/ContentTypeRepository.php
- ModelBundle/Repository/NodeRepository.php
- ModelBundle/Tests/Functional/Repository/NodeRepositoryTest.php
https://github.com/open-orchestra/open-orchestra-model-interface/pull/81/files
> remove deprecated and rename method

- ModelBundle/DataFixtures/MongoDB/LoadSiteData.php
- ModelBundle/Tests/Functional/Repository/SiteRepositoryTest.php
https://github.com/open-orchestra/open-orchestra/pull/534
https://github.com/open-orchestra/open-orchestra-base-api-bundle/pull/22
https://github.com/open-orchestra/open-orchestra-base-bundle/pull/30
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/890
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/344
https://github.com/open-orchestra/open-orchestra-front-bundle/pull/99
https://github.com/open-orchestra/open-orchestra-front-demo/pull/42
> Fix preview

- ModelBundle/Repository/NodeRepository.php
https://github.com/open-orchestra/open-orchestra-front-bundle/pull/101
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/353
https://github.com/open-orchestra/open-orchestra-model-interface/pull/85
> Add NodeRepo::findOneById

- ModelBundle/Repository/NodeRepository.php
@itkg-alavieille the search with the query aggregator was not functional, so I rollbacked it for the demo.
We should check it more precisely and write some tests
> rollback last published node search

- ModelBundle/DataFixtures/MongoDB/LoadNodeDemoData.php
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/932
https://github.com/open-orchestra/open-orchestra-display-bundle/pull/157
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/368
> Update fixtures for media in tinymce

- ModelBundle/Tests/Functional/Repository/NodeRepositoryTest.php
https://travis-ci.org/open-orchestra/open-orchestra/jobs/70350498
> adjust node repository tests

- ModelBundle/DataFixtures/MongoDB/LoadSiteData.php
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/939
https://github.com/open-orchestra/open-orchestra-media-bundle/pull/70
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/376
> rename carrousel into slideshow

- ModelBundle/Document/FieldType.php
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/953
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/382
> change type default value

- ModelBundle/Repository/NodeRepository.php
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/961
https://github.com/open-orchestra/open-orchestra-model-interface/pull/98
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/386
https://github.com/open-orchestra/open-orchestra-front-bundle/pull/111
https://github.com/open-orchestra/open-orchestra-front-demo/pull/67
https://github.com/open-orchestra/open-orchestra-provision/pull/15
https://github.com/open-orchestra/open-orchestra-docs/pull/66
> Error pages

- ModelBundle/DependencyInjection/OpenOrchestraModelExtension.php
- ModelBundle/Tests/Functional/Repository/ContentRepositoryTest.php
https://github.com/open-orchestra/open-orchestra-libs/pull/11
https://github.com/open-orchestra/open-orchestra-user-bundle/pull/71
https://github.com/open-orchestra/open-orchestra-workflow-function-bundle/pull/39
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1019
https://github.com/open-orchestra/open-orchestra-base-api-mongo-model-bundle/pull/6
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/406
https://github.com/open-orchestra/open-orchestra-base-api-bundle/pull/49
>  add strategy filter

- composer.json
Reverts open-orchestra/open-orchestra-model-bundle#408
> Revert "update mongo odm"

- ModelBundle/Repository/SiteRepository.php
https://github.com/open-orchestra/open-orchestra-front-bundle/pull/122
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/415
> update SiteRepository::findByAliasDomain to return a collection instead of a single document

- ModelBundle/DependencyInjection/OpenOrchestraModelExtension.php
- ModelBundle/Resources/config/listener.yml
- ModelBundle/Resources/config/services.yml
https://github.com/open-orchestra/open-orchestra/pull/637
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1039
https://github.com/open-orchestra/open-orchestra-workflow-function-bundle/pull/46
https://github.com/open-orchestra/open-orchestra-base-bundle/pull/43
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/421
https://github.com/open-orchestra/open-orchestra-libs/pull/19
> move annotation reader to libs

- ModelBundle/DataFixtures/MongoDB/DemoContent/HomeDataGenerator.php
- ModelBundle/DataFixtures/MongoDB/LoadContentData.php
- ModelBundle/Repository/ContentRepository.php
- ModelBundle/Repository/NodeRepository.php
- ModelBundle/Tests/Functional/Repository/ContentRepositoryTest.php
- ModelBundle/Tests/Functional/Repository/NodeRepositoryTest.php
https://github.com/open-orchestra/open-orchestra-model-interface/pull/112
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/425
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1044
> add method get by author

- ModelBundle/DataFixtures/MongoDB/DemoContent/CommunityDataGenerator.php
- ModelBundle/DataFixtures/MongoDB/DemoContent/ContactDataGenerator.php
- ModelBundle/DataFixtures/MongoDB/DemoContent/HomeDataGenerator.php
- ModelBundle/DataFixtures/MongoDB/DemoContent/LegalDataGenerator.php
- ModelBundle/DataFixtures/MongoDB/DemoContent/NewsDataGenerator.php
- ModelBundle/DataFixtures/MongoDB/DemoContent/TransverseDataGenerator.php
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/424
https://github.com/open-orchestra/open-orchestra-display-bundle/pull/171
> Update fixtures to use bbcode

- ModelBundle/DataFixtures/MongoDB/DemoContent/CommunityDataGenerator.php
- ModelBundle/DataFixtures/MongoDB/DemoContent/ContactDataGenerator.php
- ModelBundle/DataFixtures/MongoDB/DemoContent/HomeDataGenerator.php
- ModelBundle/DataFixtures/MongoDB/DemoContent/LegalDataGenerator.php
- ModelBundle/DataFixtures/MongoDB/DemoContent/NewsDataGenerator.php
- ModelBundle/DataFixtures/MongoDB/DemoContent/TransverseDataGenerator.php
- ModelBundle/DataFixtures/MongoDB/LoadNodeDemoData.php
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/428
https://github.com/open-orchestra/open-orchestra-media-bundle/pull/108
> Revert fixtures in bbcode

- ModelBundle/DataFixtures/MongoDB/LoadRoleData.php
https://github.com/open-orchestra/open-orchestra-workflow-function-bundle/pull/57
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/43
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/436
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1083
> Translate ROLE_USER

- ModelBundle/Document/Content.php
- ModelBundle/Resources/config/search/Document.Content.yml
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/457
https://github.com/open-orchestra/open-orchestra-mongo-libs/pull/2
https://github.com/open-orchestra/open-orchestra-libs/pull/30
> add configuration search columns timestampable and blameable

- ModelBundle/Form/Type/GroupSiteChoiceType.php
- ModelBundle/Form/Type/SiteThemeChoiceType.php
- ModelBundle/Form/Type/StatusChoiceType.php
- ModelBundle/Form/Type/WorkflowRoleChoiceType.php
- ModelBundle/Resources/config/form.yml
- ModelBundle/Tests/Form/Type/GroupSiteChoiceTypeTest.php
- ModelBundle/Tests/Form/Type/StatusChoiceTypeTest.php
- ModelBundle/Tests/Form/Type/ThemeChoiceTypeTest.php
- ModelBundle/Tests/Form/Type/WorkflowRoleChoiceTypeTest.php
https://github.com/open-orchestra/open-orchestra-model-interface/pull/130
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1209
https://github.com/open-orchestra/open-orchestra-workflow-function-bundle/pull/70
> rename oo_orchestra forms

- ModelBundle/Repository/ThemeRepository.php
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/469
https://github.com/open-orchestra/open-orchestra-model-interface/pull/133
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1213
> fix count of themes in datatable view

- ModelBundle/DataFixtures/MongoDB/LoadDeletedSiteContentData.php
- ModelBundle/DataFixtures/MongoDB/LoadDeletedSiteData.php
- ModelBundle/DataFixtures/MongoDB/LoadDeletedSiteNodeData.php
- ModelBundle/Repository/ContentRepository.php
- ModelBundle/Repository/NodeRepository.php
- ModelBundle/Tests/Functional/Repository/ContentRepositoryTest.php
- ModelBundle/Tests/Functional/Repository/NodeRepositoryTest.php
Depends on https://github.com/open-orchestra/open-orchestra-model-interface/pull/132.
> Add methods to filter content and nodes by author and site id.

- ModelBundle/DataFixtures/MongoDB/LoadDeletedSiteNodeData.php
- ModelBundle/DataFixtures/MongoDB/LoadNodeDemoData.php
I didn't saw other fixture priority to fix.
> change node fixtures order

- ModelBundle/Manager/DocumentForEmbedManager.php
- ModelBundle/Manager/EntityDbMapper.php
- ModelBundle/Resources/config/manager.yml
- ModelBundle/Tests/Manager/EntityDbMapperTest.php
https://github.com/open-orchestra/open-orchestra-model-interface/pull/136
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/477
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1241
> create manager to store embed document

- ModelBundle/Document/FieldType.php
https://github.com/open-orchestra/open-orchestra-workflow-function-bundle/pull/72
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/483
https://github.com/open-orchestra/open-orchestra-model-interface/pull/139
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1205
> add input view in field type

- ModelBundle/DataFixtures/MongoDB/DemoContent/TransverseDataGenerator.php
- ModelBundle/DataFixtures/MongoDB/LoadNodeDemoData.php
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/98
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/487
https://github.com/open-orchestra/open-orchestra-media-bundle/pull/142
> Alter node fixtures if media fixtures are not loaded

- ModelBundle/Resources/config/validation/node.yml
- ModelBundle/Validator/Constraints/CheckAreaPresence.php
- ModelBundle/Validator/Constraints/CheckAreaPresenceValidator.php
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1246
> deprecate model constraint

- ModelBundle/Document/Redirection.php
- ModelBundle/Repository/RedirectionRepository.php
- ModelBundle/Repository/RouteDocumentRepository.php
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1282
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/485
https://github.com/open-orchestra/open-orchestra-model-interface/pull/140
https://github.com/open-orchestra/open-orchestra-base-api-bundle/pull/65
> Clean redirection

- ModelBundle/Repository/ContentRepository.php
- ModelBundle/Repository/NodeRepository.php
- ModelBundle/Repository/RoleRepository.php
- ModelBundle/Tests/Functional/Repository/ContentRepositoryTest.php
- ModelBundle/Tests/Functional/Repository/NodeRepositoryTest.php
- ModelBundle/Tests/Functional/Repository/RoleRepositoryTest.php
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1316
https://github.com/open-orchestra/open-orchestra-model-interface/pull/141
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/494
> implement interfaces and write tests

- composer.json
https://travis-ci.org/open-orchestra/open-orchestra/jobs/99072026
> fix doctrine cache requirement php5.5

- ModelBundle/Tests/Functional/Repository/NodeRepositoryTest.php
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1328
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/502
> fix test for multirun

- ModelBundle/DataFixtures/MongoDB/DemoContent/AbstractDataGenerator.php
- ModelBundle/Document/Node.php
- composer.json
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/505
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1345
https://github.com/open-orchestra/open-orchestra-model-interface/pull/146
> add bo direction in node

- ModelBundle/Document/FieldType.php
https://github.com/open-orchestra/open-orchestra-model-interface/pull/147
https://github.com/open-orchestra/open-orchestra-elastica-bundle/pull/2
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/506
> rename unused method

- ModelBundle/Repository/NodeRepository.php
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1353
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/507
https://github.com/open-orchestra/open-orchestra-model-interface/pull/148
> Add FindByNodeIdAndNodeTypeAndSite

- ModelBundle/DataFixtures/MongoDB/DemoContent/AbstractDataGenerator.php
- ModelBundle/Document/Node.php
- ModelBundle/EventListener/UpdateSiteNodesThemeListener.php
- ModelBundle/Repository/NodeRepository.php
- ModelBundle/Resources/config/listener.yml
- ModelBundle/Resources/config/validation/node.yml
- ModelBundle/Tests/EventListener/UpdateSiteNodesThemeListenerTest.php
- ModelBundle/Tests/Functional/Repository/NodeRepositoryTest.php
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1357
https://github.com/open-orchestra/open-orchestra-model-interface/pull/150
> add defaultTheme on Nodes

- ModelBundle/DependencyInjection/Compiler/EntityResolverCompilerPass.php
https://github.com/open-orchestra/open-orchestra-base-api-mongo-model-bundle/pull/15
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1383
https://github.com/open-orchestra/open-orchestra-media-bundle/pull/157
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/515
https://github.com/open-orchestra/open-orchestra-workflow-function-bundle/pull/85
https://github.com/open-orchestra/open-orchestra-user-bundle/pull/88
> supress deprecated

- ModelBundle/Repository/NodeRepository.php
[OO-MISC] Add findByNodeAndSiteSortedByVersion() request in NodeRepository
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1254
> add findByNodeAndSiteSortedByVersion()

- ModelBundle/DataFixtures/MongoDB/DemoContent/AbstractDataGenerator.php
- ModelBundle/DataFixtures/MongoDB/DemoContent/CommunityDataGenerator.php
- ModelBundle/DataFixtures/MongoDB/DemoContent/ContactDataGenerator.php
- ModelBundle/DataFixtures/MongoDB/DemoContent/HomeDataGenerator.php
- ModelBundle/DataFixtures/MongoDB/DemoContent/LegalDataGenerator.php
- ModelBundle/DataFixtures/MongoDB/DemoContent/NewsDataGenerator.php
- ModelBundle/DataFixtures/MongoDB/DemoContent/TransverseDataGenerator.php
[OO-MISC] Refacto const display strategies name
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/518
https://github.com/open-orchestra/open-orchestra-display-bundle/pull/194
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/140
https://github.com/open-orchestra/open-orchestra-media-bundle/pull/162
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1407
> Rename strategies name

- ModelBundle/DataFixtures/MongoDB/LoadTemplateFlexData.php
- ModelBundle/Document/AreaFlex.php
- ModelBundle/Repository/TemplateFlexRepository.php
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1410
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/519
https://github.com/open-orchestra/open-orchestra-model-interface/pull/158
> add row in tempalte flex

- ModelBundle/DataFixtures/MongoDB/LoadTemplateFlexData.php
- ModelBundle/Document/AreaFlex.php
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/520
https://github.com/open-orchestra/open-orchestra-model-interface/pull/160
> add html class property

- ModelBundle/Document/AreaFlex.php
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1418
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/522
https://github.com/open-orchestra/open-orchestra-model-interface/pull/162
> Remove area

- ModelBundle/Repository/NodeRepository.php
- ModelBundle/Tests/Functional/Repository/NodeRepositoryTest.php
[OO-BUGFIX] Fix access denied error on published node access
> order findByNodeAndLanguageAndSite by version

- ModelBundle/Document/AreaFlex.php
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/525
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1435
> update set areaFlex

- ModelBundle/Repository/NodeRepository.php
- ModelBundle/Tests/Functional/Repository/NodeRepositoryTest.php
[OO-MISC] Node order validator don't checks deleted nodes
> update unique node order validation

- ModelBundle/Document/FieldType.php
[OO-FEATURE] Add sortable option for the datatable
https://github.com/open-orchestra/open-orchestra-model-interface/pull/165
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/528
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1451
> add orderable option content attribute

- ModelBundle/DataFixtures/MongoDB/DemoContent/AbstractDataGenerator.php
- ModelBundle/DataFixtures/MongoDB/DemoContent/Error404DataGenerator.php
- ModelBundle/DataFixtures/MongoDB/DemoContent/Error503DataGenerator.php
- ModelBundle/DataFixtures/MongoDB/LoadNodeDemoData.php
- ModelBundle/Tests/Functional/Repository/NodeRepositoryTest.php
https://github.com/open-orchestra/open-orchestra-front-bundle/pull/142
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/527
> 1 1 add error pages fixtures

- ModelBundle/DataFixtures/MongoDB/AbstractLoadSiteData.php
- ModelBundle/DataFixtures/MongoDB/LoadDemoSiteData.php
- ModelBundle/DataFixtures/MongoDB/LoadRedirectionData.php
- ModelBundle/DataFixtures/MongoDB/LoadSiteData.php
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/530
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/161
https://github.com/open-orchestra/open-orchestra-workflow-function-bundle/pull/89
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1461
> update fixture production

- ModelBundle/Migrations/MongoDB/Version20160304170101.php
- composer.json
[OO-MISC] Add migration script for update of user groups collection,  futher [documation about migration](http://open-orchestra.readthedocs.org/en/latest/hosting_guide/migration.html)
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/531
https://github.com/open-orchestra/open-orchestra/pull/853
> add bundle migration and script user group

- ModelBundle/DataFixtures/MongoDB/LoadContentTypeData.php
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1491
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/532
> add searchable field type

- ModelBundle/DataFixtures/MongoDB/LoadContentNewsData.php
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1507
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/174
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/535
> Update functional fixtures for content including a oo_media_choice

- ModelBundle/DataFixtures/MongoDB/DemoContent/AbstractDataGenerator.php
- ModelBundle/DataFixtures/MongoDB/DemoContent/TransverseDataGenerator.php
- ModelBundle/DataFixtures/MongoDB/LoadNodeDemoData.php
- ModelBundle/Document/Node.php
- ModelBundle/Document/Template.php
[OO-BUGFIX] Demo fixtures are updated to present block usage references
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1540
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/191
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/542
https://github.com/open-orchestra/open-orchestra-model-interface/pull/173
> 1.1 Physically remove deleted blocks

- ModelBundle/Document/Content.php
- ModelBundle/Document/ContentType.php
- ModelBundle/EventListener/UpdateSiteNodesThemeListener.php
- ModelBundle/Repository/NodeRepository.php
- ModelBundle/Repository/RoleRepository.php
https://github.com/open-orchestra/open-orchestra-base-api-bundle/pull/77
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1562
https://github.com/open-orchestra/open-orchestra-elastica-bundle/pull/26
https://github.com/open-orchestra/open-orchestra-libs/pull/44
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/551
> Remove unused uses

- ModelBundle/DataFixtures/MongoDB/DemoContent/TransverseDataGenerator.php
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/550
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1561
> add translation global page

- ModelBundle/DataFixtures/MongoDB/LoadRoleData.php
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/552
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1567
> remove role user of role transition

- ModelBundle/EventListener/GenerateIdListener.php
- ModelBundle/Tests/EventListener/GenerateIdListenerTest.php
this allows to change the reader used at runtime
> use an interface as type hint in generate id listener

- ModelBundle/EventListener/GenerateIdListener.php
- ModelBundle/Tests/EventListener/GenerateIdListenerTest.php
> use an interface as type hint in generate id listener (branch 1.0)

- ModelBundle/DataFixtures/MongoDB/DemoContent/AbstractDataGenerator.php
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/555
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1574
> fix fixture block language list

- ModelBundle/DataFixtures/MongoDB/DemoContent/CommunityDataGenerator.php
- ModelBundle/DataFixtures/MongoDB/DemoContent/ContactDataGenerator.php
- ModelBundle/DataFixtures/MongoDB/DemoContent/Error404DataGenerator.php
- ModelBundle/DataFixtures/MongoDB/DemoContent/Error503DataGenerator.php
- ModelBundle/DataFixtures/MongoDB/DemoContent/HomeDataGenerator.php
- ModelBundle/DataFixtures/MongoDB/DemoContent/LegalDataGenerator.php
- ModelBundle/DataFixtures/MongoDB/DemoContent/NewsDataGenerator.php
- ModelBundle/DataFixtures/MongoDB/DemoContent/NodeRootFunctionalDataGenerator.php
- ModelBundle/DataFixtures/MongoDB/DemoContent/TransverseDataGenerator.php
- ModelBundle/Document/Node.php
- ModelBundle/EventListener/UpdateBoLabelNodeFieldListener.php
- ModelBundle/Migrations/MongoDB/Version20160421105828.php
- ModelBundle/Resources/config/listener.yml
- ModelBundle/Resources/config/validation/node.yml
- ModelBundle/Tests/EventListener/UpdateBoLabelNodeFieldListenerTest.php
[OO-FEATURE] Adding attribute ``boLabel`` on Node , used to generate tree in the Back Office
[OO-FEATURE] Add migration for attribute ``boLabel``
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1586
https://github.com/open-orchestra/open-orchestra-model-interface/pull/179
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/561
> add attribute boLabel

- ModelBundle/Migrations/MongoDB/Version20160304170101.php
- ModelBundle/Migrations/MongoDB/Version20160422151315.php
[OO-FEATURE] Add script migration to rename role  ROLE_ACCESS_MOVE_NODE by ROLE_ACCESS_MOVE_TREE
> Add migration rename role

- ModelBundle/DataFixtures/MongoDB/LoadNodeRootFunctionalDemoData.php
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1599
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/565
> fix fixture block global page

- ModelBundle/DataFixtures/MongoDB/LoadDemoSiteData.php
https://github.com/open-orchestra/open-orchestra/pull/899
https://github.com/open-orchestra/open-orchestra-media-demo/pull/75
https://github.com/open-orchestra/open-orchestra-front-demo/pull/201
https://github.com/open-orchestra/open-orchestra-docs/pull/183
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/567
> update host 1.2 site fixture

- ModelBundle/DataFixtures/MongoDB/LoadDemoSiteData.php
https://github.com/open-orchestra/open-orchestra/pull/900
https://github.com/open-orchestra/open-orchestra-media-demo/pull/76
https://github.com/open-orchestra/open-orchestra-front-demo/pull/202
https://github.com/open-orchestra/open-orchestra-docs/pull/187
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/568
> update fixture site host 1.1

- ModelBundle/DataFixtures/MongoDB/LoadSiteData.php
https://github.com/open-orchestra/open-orchestra/pull/901
https://github.com/open-orchestra/open-orchestra-media-demo/pull/77
https://github.com/open-orchestra/open-orchestra-front-demo/pull/203
https://github.com/open-orchestra/open-orchestra-docs/pull/188
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/569
https://github.com/open-orchestra/open-orchestra-provision/pull/37
> update fixture site host 1.0

- ModelBundle/DataFixtures/MongoDB/LoadDemoSiteData.php
https://github.com/open-orchestra/open-orchestra/pull/904
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/570
https://github.com/open-orchestra/open-orchestra-media-demo/pull/80
https://github.com/open-orchestra/open-orchestra-front-demo/pull/206
https://github.com/itkg/open-orchestra-internals/pull/15
> update site alias inte

- ModelBundle/DataFixtures/MongoDB/LoadDemoSiteData.php
- ModelBundle/Tests/Functional/Repository/SiteRepositoryTest.php
https://github.com/open-orchestra/open-orchestra-media-demo/pull/81
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/572
https://github.com/open-orchestra/open-orchestra/pull/905
https://github.com/itkg/open-orchestra-internals/pull/16
https://github.com/open-orchestra/open-orchestra-front-demo/pull/207
> update host inte 1.1

- ModelBundle/DataFixtures/MongoDB/LoadSiteData.php
https://github.com/open-orchestra/open-orchestra/pull/906
https://github.com/itkg/open-orchestra-internals/pull/16
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/573
https://github.com/open-orchestra/open-orchestra-media-demo/pull/82
https://github.com/open-orchestra/open-orchestra-front-demo/pull/208
> update fixture host inte 1.0

- ModelBundle/Migrations/MongoDB/Version20160317140327.php
[OO-FEATURE] Update route in database after site migration and site-alias update
> update route on site alias update during migration

- ModelBundle/Migrations/MongoDB/Version20160511093334.php
[BUGFIX] Adding migration for attributes of configurable content
> add migration block configurable content

- ModelBundle/DataFixtures/MongoDB/LoadSiteData.php
[OO-MISC] The sample block is removed
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1653
https://github.com/open-orchestra/open-orchestra-display-bundle/pull/211
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/578
> Remove Sample block

- ModelBundle/Repository/SiteRepository.php
[OO-BUGFIX] Fix the bad return type of SiteRepository::findByAliasDomain
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/585
https://github.com/open-orchestra/open-orchestra-display-bundle/pull/218
> 1 1 fix find by alias domain

- ModelBundle/Repository/NodeRepository.php
[OO-FEATURE] Add a NodeRepository::findOneByNodeAndSite method
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1738
https://github.com/open-orchestra/open-orchestra-model-interface/pull/191
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/591
> Add NodeRepository::findOneByNodeAndSite

- ModelBundle/Repository/NodeRepository.php
[OO-FEATURE] Add a NodeRepository::findOneByNodeAndSite method
https://github.com/open-orchestra/open-orchestra-model-interface/pull/193
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/592
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1741
> 1 2 fix nodegrouprole other currentsite

- ModelBundle/Migrations/MongoDB/Version20160614102602.php
[OO-FEATURE] Add a  1.1.* -> 1.2.0 migration script to update the site meta
> Add migration script to upgrade multi languages site meta

- ModelBundle/Document/AbstractStatus.php
fix wokflow status code langue index https://github.com/open-orchestra/open-orchestra-workflow-function-bundle/issues/114
@KevinArtus
> fix workflow status

- ModelBundle/Document/AbstractStatus.php
cherry-pick https://github.com/open-orchestra/open-orchestra-model-bundle/pull/601
> Fix wolkflow status 1.2

- ModelBundle/Repository/RepositoryTrait/KeywordableTrait.php
- ModelBundle/Tests/Functional/Repository/ContentRepositoryTest.php
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1783
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/608
> fix functional test keywords

- ModelBundle/Resources/config/form.yml
- ModelBundle/Resources/config/helper.yml
- ModelBundle/Resources/config/listener.yml
- ModelBundle/Resources/config/manager.yml
- ModelBundle/Resources/config/saver.yml
- ModelBundle/Resources/config/transformer.yml
- ModelBundle/Resources/config/validator.yml
[OO-FEATURE] Adding yaml compatibility for Symfony 3
> add compatibility yaml symfony 3.0

- ModelBundle/Tests/Functional/Repository/ContentRepositoryTest.php
https://github.com/open-orchestra/open-orchestra-libs/pull/62
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/614
> fix functional test

- ModelBundle/Resources/translations/validators.de.yml
- ModelBundle/Resources/translations/validators.en.yml
- ModelBundle/Resources/translations/validators.fr.yml
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1809
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/615
> update message invalid character

- ModelBundle/Resources/config/validation/node.yml
[OO-BUGFIX] Removing boLabel of the error nodes
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1822
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/620
> add group validation error node bo label

- ModelBundle/Resources/config/validation/node.yml
- ModelBundle/Tests/Functional/Repository/ContentRepositoryTest.php
[OO-BUGFIX] Removing boLabel of the error nodes
cherry-pick https://github.com/open-orchestra/open-orchestra-model-bundle/pull/620
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1828
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/622
> add group validation error node bo label (#620)

- ModelBundle/Repository/NodeRepository.php
[OO-MISC] optimize route generation on node update
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1818
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/618
https://github.com/open-orchestra/open-orchestra-model-interface/pull/210
> Optimize route creation

- ModelBundle/Repository/NodeRepository.php
[OO-MISC] optimize route generation on node update
> 1.1 optimize route creation

- ModelBundle/Repository/NodeRepository.php
[OO-DEPRECATED] NodeRepository::findByPathCurrentlyPublished
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1840
https://github.com/open-orchestra/open-orchestra-model-interface/pull/214
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/630
https://github.com/open-orchestra/open-orchestra/pull/1014
> add language in parameter for route generation

- ModelBundle/DataFixtures/MongoDB/LoadDeletedSiteNodeData.php
https://github.com/open-orchestra/open-orchestra-front-demo/pull/272
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/633
> add route document nodes deleted site

- ModelBundle/Repository/ContentRepository.php
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/632
https://github.com/open-orchestra/open-orchestra-model-interface/pull/216
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/277
> add find by id content repository

- ModelBundle/Document/Node.php
- ModelBundle/Repository/NodeRepository.php
https://github.com/open-orchestra/open-orchestra-display-bundle/pull/239
https://github.com/open-orchestra/open-orchestra-model-interface/pull/218
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/635
https://github.com/open-orchestra/open-orchestra-elastica-bundle/pull/53
> find all node currently publish

- ModelBundle/DataFixtures/MongoDB/DemoContent/AbstractDataGenerator.php
- ModelBundle/DataFixtures/MongoDB/DemoContent/CommunityDataGenerator.php
- ModelBundle/DataFixtures/MongoDB/DemoContent/ContactDataGenerator.php
- ModelBundle/DataFixtures/MongoDB/DemoContent/Error404DataGenerator.php
- ModelBundle/DataFixtures/MongoDB/DemoContent/Error503DataGenerator.php
- ModelBundle/DataFixtures/MongoDB/DemoContent/LegalDataGenerator.php
- ModelBundle/DataFixtures/MongoDB/DemoContent/NewsDataGenerator.php
- ModelBundle/DataFixtures/MongoDB/DemoContent/NodeRootFunctionalDataGenerator.php
- ModelBundle/DataFixtures/MongoDB/LoadNodeRootFunctionalDemoData.php
- ModelBundle/Migrations/MongoDB/Version20160829153541.php
- ModelBundle/Migrations/MongoDB/config/private_block_migration.yml
[OO-FEATURE] Add a query parameter `cache=private` in the url when a private block is rendering
https://github.com/open-orchestra/open-orchestra-docs/pull/229
https://github.com/open-orchestra/open-orchestra-provision/pull/41
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/636
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1853
https://github.com/open-orchestra/open-orchestra-front-bundle/pull/191
> specify block cache in fixutre

- ModelBundle/DataFixtures/MongoDB/AbstractLoadStatus.php
- ModelBundle/DataFixtures/MongoDB/LoadContentTypeData.php
- ModelBundle/DataFixtures/MongoDB/LoadRoleDataFunctional.php
- ModelBundle/DataFixtures/MongoDB/LoadRoleDataProduction.php
- ModelBundle/Document/AbstractStatus.php
- ModelBundle/Document/ContentType.php
- ModelBundle/Document/EmbedStatus.php
- ModelBundle/Document/FieldType.php
- ModelBundle/Document/Role.php
- ModelBundle/Document/Site.php
- ModelBundle/Document/TranslatedValue.php
- ModelBundle/Form/Type/StatusChoiceType.php
- ModelBundle/Migrations/MongoDB/Version20160831141739.php
- ModelBundle/Resources/config/form.yml
- ModelBundle/Resources/config/resolve_document.yml
- ModelBundle/Resources/config/search/Document.Content.yml
- ModelBundle/Resources/config/validation/translatedValue.yml
- ModelBundle/Tests/Form/DataTransformer/EmbedStatusToStatusTransformerTest.php
- ModelBundle/Tests/Form/Type/StatusChoiceTypeTest.php
[OO-FEATURES] Improvement of translation storage
[OO-DEPRECATED] TranslatedValue is deprecated and  will be removed in 2.0
https://github.com/open-orchestra/open-orchestra-workflow-function-bundle/pull/145
https://github.com/open-orchestra/open-orchestra-media-bundle/pull/232
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/280
https://github.com/open-orchestra/open-orchestra-mongo-libs/pull/48
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/638
https://github.com/open-orchestra/open-orchestra-model-interface/pull/220
https://github.com/open-orchestra/open-orchestra/pull/1025
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1858
same PR that https://github.com/open-orchestra/open-orchestra-model-bundle/pull/638
> update translation storage

- ModelBundle/Document/ContentType.php
[OO-FEATURE] optional version for content
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1859
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/639
https://github.com/open-orchestra/open-orchestra-model-interface/pull/221
https://github.com/open-orchestra/open-orchestra-mongo-libs/pull/49
> optional version for content

- ModelBundle/Repository/NodeRepository.php
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/641
https://github.com/open-orchestra/open-orchestra-model-interface/pull/223
https://github.com/open-orchestra/open-orchestra-elastica-bundle/pull/53
> add method to count all node published by type

- ModelBundle/Repository/NodeRepository.php
[OO-BUGFIX] When theme is updated, modification is updated in node
https://github.com/open-orchestra/open-orchestra-front-demo/pull/282
https://github.com/open-orchestra/open-orchestra/pull/1026
https://github.com/open-orchestra/open-orchestra-model-interface/pull/222
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/640
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1860
> add find nodes by themes

- ModelBundle/DataFixtures/MongoDB/AbstractLoadStatus.php
- ModelBundle/DataFixtures/MongoDB/LoadContentData.php
- ModelBundle/DataFixtures/MongoDB/LoadStatusData.php
- ModelBundle/Document/AbstractStatus.php
- ModelBundle/Document/ContentType.php
- ModelBundle/Document/EmbedStatus.php
- ModelBundle/Migrations/MongoDB/Version20160906143157.php
[OO-FEATURE] add possibility to create status published and editable
https://github.com/open-orchestra/open-orchestra-model-interface/pull/226
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/644
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1867
> Editable published status

- ModelBundle/Document/AbstractKeyword.php
- ModelBundle/Repository/KeywordRepository.php
- ModelBundle/Repository/RepositoryTrait/UseTrackableTrait.php
[OO-FEATURE] Add use tracking of keywords
https://github.com/open-orchestra/open-orchestra-mongo-libs/pull/50
https://github.com/open-orchestra/open-orchestra-model-interface/pull/225
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/643
https://github.com/open-orchestra/open-orchestra-media-bundle/pull/233
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/282
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1862
https://github.com/open-orchestra/open-orchestra-bbcode-bundle/pull/25
https://github.com/open-orchestra/open-orchestra/pull/1027
> 1 2 keyword references

- ModelBundle/DataFixtures/MongoDB/AbstractLoadStatus.php
- ModelBundle/DataFixtures/MongoDB/DemoContent/AutoPublishDataGenerator.php
- ModelBundle/DataFixtures/MongoDB/LoadNodeRootFunctionalDemoData.php
- ModelBundle/DataFixtures/MongoDB/LoadStatusData.php
- ModelBundle/DataFixtures/MongoDB/LoadStatusDataFunctional.php
- ModelBundle/Document/AbstractStatus.php
- ModelBundle/Document/Node.php
- ModelBundle/EventListener/AutoUnpublishStatusListener.php
- ModelBundle/Repository/NodeRepository.php
- ModelBundle/Repository/StatusRepository.php
- ModelBundle/Resources/config/listener.yml
- ModelBundle/Tests/EventListener/AutoUnpublishStatusListenerTest.php
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1845
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/634
https://github.com/open-orchestra/open-orchestra-model-interface/pull/217
https://github.com/open-orchestra/open-orchestra-provision/pull/40
https://github.com/open-orchestra/open-orchestra-docs/pull/230
https://github.com/open-orchestra/open-orchestra/pull/1028
> 1.2 auto publishing

- ModelBundle/DataFixtures/MongoDB/AbstractLoadStatus.php
- ModelBundle/DataFixtures/MongoDB/LoadContentTypeData.php
- ModelBundle/DataFixtures/MongoDB/LoadStatusData.php
- ModelBundle/Document/AbstractStatus.php
- ModelBundle/Document/ContentType.php
- ModelBundle/Document/EmbedStatus.php
- ModelBundle/EventListener/SetInitialStatusListener.php
- ModelBundle/Migrations/MongoDB/Version20160907153954.php
- ModelBundle/Repository/StatusRepository.php
[OO-FEATURE] add optionally statusable for content
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1869
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/646
https://github.com/open-orchestra/open-orchestra-model-interface/pull/227
> add optionally statusable

- ModelBundle/Document/Content.php
- ModelBundle/Repository/ContentRepository.php
[OO-FEATURE] Content usage is now trackable
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1875
https://github.com/open-orchestra/open-orchestra-model-interface/pull/228
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/647
> Make content usage trackable

- ModelBundle/Repository/ContentRepository.php
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1885
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/649
https://github.com/open-orchestra/open-orchestra-model-interface/pull/230
> Add ContentRepository::countByContentType

- ModelBundle/DependencyInjection/Configuration.php
- ModelBundle/Document/EmbedKeyword.php
- ModelBundle/Repository/ContentRepository.php
- ModelBundle/Resources/config/resolve_document.yml
- ModelBundle/Resources/config/validation/translatedValue.yml
https://github.com/open-orchestra/open-orchestra-mongo-libs/pull/52
https://github.com/open-orchestra/open-orchestra-model-interface/pull/231
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/650
https://github.com/open-orchestra/open-orchestra-media-bundle/pull/235
https://github.com/open-orchestra/open-orchestra-elastica-bundle/pull/56
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1890
https://github.com/open-orchestra/open-orchestra-libs/pull/64
> update deprecated annotation

- ModelBundle/DataFixtures/MongoDB/LoadDemoSiteData.php
[OO-MISC] Block Gmap and AddThis are disabled
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/656
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1895
> disable block gmap and addThis

- ModelBundle/Document/Theme.php
cherry-pick https://github.com/open-orchestra/open-orchestra-model-bundle/pull/657
> fix search sort theme name (#657)

- ModelBundle/DataFixtures/MongoDB/LoadContentTypeData.php
- ModelBundle/Document/ContentType.php
- ModelBundle/EventListener/SetInitialStatusListener.php
- ModelBundle/Migrations/MongoDB/Version20160907153954.php
[OO-BUGFIX] Enhance non statusable and versionable in content type
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1899
https://github.com/open-orchestra/open-orchestra-workflow-function-bundle/pull/147
https://github.com/open-orchestra/open-orchestra-model-interface/pull/234
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/658
> enhance statusable content type interface

- ModelBundle/Document/TrashItem.php
- ModelBundle/Migrations/MongoDB/Version20161006100559.php
[OO-FEATURE] add possibility to pre-filter data in table view (use case, filter on current site for trashcan)
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1916
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/661
https://github.com/open-orchestra/open-orchestra-mongo-libs/pull/54
https://github.com/open-orchestra/open-orchestra-libs/pull/65
https://github.com/open-orchestra/open-orchestra-base-api-bundle/pull/108
https://github.com/open-orchestra/open-orchestra-workflow-function-bundle/pull/150
https://github.com/open-orchestra/open-orchestra/pull/1047
> add site on trash item

- ModelBundle/Document/TrashItem.php
- ModelBundle/Migrations/MongoDB/Version20161006100559.php
[OO-FEATURE] add possibility to pre-filter data in table view (use case, filter on current site for trashcan)
> 1.2 add site trash item

- ModelBundle/Repository/ContentRepository.php
[OO-BUGFIX] Content search filter content with the current site 
https://github.com/open-orchestra/open-orchestra-display-bundle/pull/245
https://github.com/open-orchestra/open-orchestra-model-interface/pull/238
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/662
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1925
> fix content search, add filter current site

- ModelBundle/Repository/ContentRepository.php
[OO-BUGFIX] Content search filter content with the current site
https://github.com/open-orchestra/open-orchestra-display-bundle/pull/246
https://github.com/open-orchestra/open-orchestra-model-interface/pull/242
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/664
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1932
cherry pick https://github.com/open-orchestra/open-orchestra-model-bundle/pull/662
> Fix list content content search with currentsite

- ModelBundle/DataFixtures/MongoDB/LoadDemoSiteData.php
cherry pick 
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/656
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1895
> disable block gmap add this

- ModelBundle/Repository/NodeRepository.php
[OO-MISC] Add NodeRepository::findByIncludedPathSiteIdAndLanguage
[OO-MISC] Add NodeRepository::findByPathCurrentlyPublishedAndLanguage
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/673
https://github.com/open-orchestra/open-orchestra-model-interface/pull/246
> add language in parameter for route generation (#630)

- ModelBundle/DataFixtures/MongoDB/DemoContent/HomeDataGenerator.php
- ModelBundle/DataFixtures/MongoDB/LoadDemoSiteData.php
[OO-MISC] Rewrite alias to always have a language prefix on translated sites
> Update alias fixtures (#674)

- ModelBundle/DataFixtures/MongoDB/DemoContent/HomeDataGenerator.php
- ModelBundle/DataFixtures/MongoDB/LoadDemoSiteData.php
[OO-MISC] Rewrite alias to always have a language prefix on translated sites
> Update alias fixtures (#674) (#675)

- ModelBundle/Document/Node.php
- ModelBundle/Repository/NodeRepository.php
- ModelBundle/Repository/RepositoryTrait/UseTrackableTrait.php
[OO-FEATURE] Add use reference when node is used in node
https://github.com/open-orchestra/open-orchestra-display-bundle/pull/247
https://github.com/open-orchestra/open-orchestra-model-interface/pull/243
https://github.com/open-orchestra/open-orchestra-mongo-libs/pull/60
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/667
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1934
https://github.com/open-orchestra/open-orchestra/pull/1053
> Add reference node

- ModelBundle/Repository/ContentRepository.php
[OO-FEATURE] synchronize all contents with statusable state in content type
https://github.com/open-orchestra/open-orchestra/pull/1074
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1970
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/681
https://github.com/open-orchestra/open-orchestra-model-interface/pull/249
> add subscriber and update on statusable content type changing

- ModelBundle/Document/Site.php
- ModelBundle/Document/SiteAlias.php
- ModelBundle/Repository/ContentRepository.php
[OO-FEATURE] add tabulation, fieldset and two columns checkbox in forms
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/682
https://github.com/open-orchestra/open-orchestra-model-interface/pull/250
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1972
https://github.com/open-orchestra/open-orchestra-elastica-bundle/pull/59
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/317
> Add tabulation site

- ModelBundle/Repository/RedirectionRepository.php
https://github.com/open-orchestra/open-orchestra/pull/1082
https://github.com/open-orchestra/open-orchestra-model-interface/pull/252
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/684
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1985
> add find redirection by siteId

- ModelBundle/Repository/RedirectionRepository.php
cherry pick https://github.com/open-orchestra/open-orchestra-model-bundle/pull/684
> add find redirection by siteId (#684)

- ModelBundle/DataFixtures/MongoDB/DemoContent/Error404DataGenerator.php
- ModelBundle/DataFixtures/MongoDB/DemoContent/Error503DataGenerator.php
- ModelBundle/DataFixtures/MongoDB/DemoContent/NodeRootFunctionalDataGenerator.php
- ModelBundle/Repository/NodeRepository.php
- ModelBundle/Repository/StatusRepository.php
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/690
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1998
https://github.com/open-orchestra/open-orchestra-model-interface/pull/257
https://github.com/open-orchestra/open-orchestra/pull/1088
> Add tree node

- ModelBundle/Repository/NodeRepository.php
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/691
https://github.com/open-orchestra/open-orchestra-model-interface/pull/258
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2001
https://github.com/open-orchestra/open-orchestra/pull/1093
https://github.com/open-orchestra/open-orchestra-libs/pull/70
> Add table node

- ModelBundle/DataFixtures/MongoDB/AbstractLoadStatus.php
- ModelBundle/DataFixtures/MongoDB/LoadStatusData.php
- ModelBundle/DataFixtures/MongoDB/LoadWorkflowProfileDataFunctional.php
- ModelBundle/Document/AbstractStatus.php
- ModelBundle/Document/EmbedStatus.php
- ModelBundle/Document/Node.php
- ModelBundle/EventListener/TranslationStatusListener.php
- ModelBundle/Repository/NodeRepository.php
- ModelBundle/Repository/StatusRepository.php
- ModelBundle/Resources/config/listener.yml
- ModelBundle/Tests/EventListener/TranslationStatusListener.php
https://github.com/open-orchestra/open-orchestra-front-bundle/pull/208
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/694
https://github.com/open-orchestra/open-orchestra/pull/1100
https://github.com/open-orchestra/open-orchestra-model-interface/pull/261
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2009
> update node form

- composer.json
https://github.com/open-orchestra/open-orchestra/pull/1108
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/704
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/328
> add migration bundle

- ModelBundle/DataFixtures/MongoDB/AbstractLoadStatus.php
- ModelBundle/Document/AbstractStatus.php
- ModelBundle/Document/Content.php
- ModelBundle/Document/EmbedStatus.php
- ModelBundle/Document/Node.php
- ModelBundle/EventListener/AutoUnpublishStatusListener.php
- ModelBundle/EventListener/InitialStatusListener.php
- ModelBundle/Repository/ContentRepository.php
- ModelBundle/Repository/NodeRepository.php
- ModelBundle/Repository/StatusRepository.php
- ModelBundle/Resources/config/validation/embedStatus.yml
- ModelBundle/Resources/config/validation/status.yml
- ModelBundle/Tests/EventListener/AutoUnpublishStatusListenerTest.php
- ModelBundle/Tests/EventListener/InitialStatusListenerTest.php
- ModelBundle/Tests/EventListener/TranslationStatusListener.php
[OO-MISC] Refacto status attributes
https://github.com/open-orchestra/open-orchestra/pull/1110
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2030
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/705
https://github.com/open-orchestra/open-orchestra-model-interface/pull/266
> Refacto status attributes

- ModelBundle/Document/Site.php
- ModelBundle/Repository/SiteRepository.php
- ModelBundle/Tests/DependencyInjection/OpenOrchestraModelExtensionTest.php
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/713
https://github.com/open-orchestra/open-orchestra-model-interface/pull/273
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2049
https://github.com/open-orchestra/open-orchestra/pull/1122
> add list site

- ModelBundle/Document/WorkflowProfile.php
- ModelBundle/Repository/WorkflowProfileRepository.php
- ModelBundle/Resources/config/validation/contentType.yml
- ModelBundle/Resources/config/validation/embedStatus.yml
- ModelBundle/Resources/config/validation/fieldType.yml
- ModelBundle/Resources/config/validation/status.yml
- ModelBundle/Resources/config/validation/workflow_profile.yml
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/712
https://github.com/open-orchestra/open-orchestra-model-interface/pull/272
https://github.com/open-orchestra/open-orchestra/pull/1121
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2046
> Add paginate workflow

- ModelBundle/DataFixtures/MongoDB/LoadNodeRootFunctionalDemoData.php
- ModelBundle/Document/Area.php
- ModelBundle/Document/Block.php
- ModelBundle/Repository/NodeRepository.php
- ModelBundle/Validator/Constraints/PreventProhibitedStatusChangeValidator.php
https://github.com/open-orchestra/open-orchestra-model-interface/pull/270
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/709
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/334
https://github.com/open-orchestra/open-orchestra/pull/1119
https://github.com/open-orchestra/open-orchestra-elastica-bundle/pull/62
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2042
> Add edit node

- ModelBundle/Repository/SiteRepository.php
https://github.com/open-orchestra/open-orchestra-front-demo/pull/328
https://github.com/open-orchestra/open-orchestra/pull/1124
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2050
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/714
https://github.com/open-orchestra/open-orchestra-model-interface/pull/274
> remove methode delete multiple site

- ModelBundle/Repository/StatusRepository.php
- ModelBundle/Tests/Form/DataTransformer/EmbedStatusToStatusTransformerTest.php
Add status edition screen
https://github.com/open-orchestra/open-orchestra/pull/1118
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2040
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/708
https://github.com/open-orchestra/open-orchestra-model-interface/pull/269
> 2 0 status edition

- ModelBundle/DataFixtures/MongoDB/LoadContentTypeData.php
- ModelBundle/Document/ContentType.php
- ModelBundle/Document/FieldType.php
https://github.com/open-orchestra/open-orchestra-model-interface/pull/277
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/718
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2058
> add edit content type

- ModelBundle/Document/ContentType.php
- ModelBundle/Repository/ContentTypeRepository.php
- ModelBundle/Tests/DependencyInjection/OpenOrchestraModelExtensionTest.php
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2056
https://github.com/open-orchestra/open-orchestra-model-interface/pull/276
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/717
https://github.com/open-orchestra/open-orchestra/pull/1126
> Content type list

- ModelBundle/DataFixtures/MongoDB/DemoContent/AbstractDataGenerator.php
- ModelBundle/DataFixtures/MongoDB/DemoContent/AutoPublishDataGenerator.php
- ModelBundle/DataFixtures/MongoDB/DemoContent/CommunityDataGenerator.php
- ModelBundle/DataFixtures/MongoDB/DemoContent/ContactDataGenerator.php
- ModelBundle/DataFixtures/MongoDB/DemoContent/Error404DataGenerator.php
- ModelBundle/DataFixtures/MongoDB/DemoContent/Error503DataGenerator.php
- ModelBundle/DataFixtures/MongoDB/DemoContent/LegalDataGenerator.php
- ModelBundle/DataFixtures/MongoDB/DemoContent/NewsDataGenerator.php
- ModelBundle/DataFixtures/MongoDB/DemoContent/NodeRootFunctionalDataGenerator.php
- ModelBundle/DataFixtures/MongoDB/LoadNodeRootFunctionalDemoData.php
- ModelBundle/Document/Block.php
- ModelBundle/Repository/BlockRepository.php
- ModelBundle/Repository/NodeRepository.php
https://github.com/open-orchestra/open-orchestra-elastica-bundle/pull/63
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/336
https://github.com/open-orchestra/open-orchestra-model-interface/pull/275
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/716
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2054
> shared block list

- ModelBundle/Document/WorkflowProfile.php
- ModelBundle/Repository/StatusRepository.php
- ModelBundle/Repository/WorkflowProfileRepository.php
[OO-FEATURE] Add workflow transitions form
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2064
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/720
https://github.com/open-orchestra/open-orchestra-model-interface/pull/278
> 2 0 workflow transitions

- ModelBundle/DataFixtures/MongoDB/LoadContentData.php
- ModelBundle/DataFixtures/MongoDB/LoadContentTypeData.php
- ModelBundle/Repository/ContentRepository.php
- ModelBundle/Resources/config/search/Document.Content.yml
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/722
https://github.com/open-orchestra/open-orchestra-model-interface/pull/280
https://github.com/open-orchestra/open-orchestra-mongo-libs/pull/66
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2068
https://github.com/open-orchestra/open-orchestra-libs/pull/74
https://github.com/open-orchestra/open-orchestra/pull/1131
> Add content list

- ModelBundle/Document/WorkflowProfile.php
- ModelBundle/Resources/config/validation/node.yml
- ModelBundle/Validator/Constraints/PreventProhibitedStatusChangeValidator.php
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/723
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2072
> add validator template required

- ModelBundle/Document/AbstractKeyword.php
- ModelBundle/Repository/KeywordRepository.php
- ModelBundle/Tests/DependencyInjection/OpenOrchestraModelExtensionTest.php
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2066
https://github.com/open-orchestra/open-orchestra/pull/1129
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/721
https://github.com/open-orchestra/open-orchestra-model-interface/pull/279
> add keyword list and form

- ModelBundle/Document/Area.php
- ModelBundle/Repository/BlockRepository.php
https://github.com/open-orchestra/open-orchestra-model-interface/pull/281
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/724
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2075
https://github.com/open-orchestra/open-orchestra/pull/1133
> Update add block area

- ModelBundle/Document/Block.php
- ModelBundle/Repository/NodeRepository.php
https://github.com/open-orchestra/open-orchestra/pull/1135
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2079
https://github.com/open-orchestra/open-orchestra-model-interface/pull/283
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/726
> copy to translate block

- ModelBundle/Repository/RedirectionRepository.php
- ModelBundle/Tests/DependencyInjection/OpenOrchestraModelExtensionTest.php
[OO-FEATURE] Add redirection feature
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2076
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/725
https://github.com/open-orchestra/open-orchestra-model-interface/pull/282
https://github.com/open-orchestra/open-orchestra/pull/1134
> 2 0 redirection

- ModelBundle/DataFixtures/MongoDB/DemoContent/AbstractDataGenerator.php
- ModelBundle/DataFixtures/MongoDB/DemoContent/AutoPublishDataGenerator.php
- ModelBundle/DataFixtures/MongoDB/DemoContent/CommunityDataGenerator.php
- ModelBundle/DataFixtures/MongoDB/DemoContent/ContactDataGenerator.php
- ModelBundle/DataFixtures/MongoDB/DemoContent/Error404DataGenerator.php
- ModelBundle/DataFixtures/MongoDB/DemoContent/Error503DataGenerator.php
- ModelBundle/DataFixtures/MongoDB/DemoContent/HomeDataGenerator.php
- ModelBundle/DataFixtures/MongoDB/DemoContent/LegalDataGenerator.php
- ModelBundle/DataFixtures/MongoDB/DemoContent/NewsDataGenerator.php
- ModelBundle/DataFixtures/MongoDB/DemoContent/NodeRootFunctionalDataGenerator.php
- ModelBundle/DataFixtures/MongoDB/LoadContentData.php
- ModelBundle/DataFixtures/MongoDB/LoadContentNewsData.php
- ModelBundle/DataFixtures/MongoDB/LoadContentThousandData.php
- ModelBundle/DataFixtures/MongoDB/LoadDeletedSiteNodeData.php
- ModelBundle/DataFixtures/MongoDB/LoadStatusData.php
- ModelBundle/Form/Type/StatusChoiceType.php
- ModelBundle/Repository/ContentRepository.php
- ModelBundle/Repository/NodeRepository.php
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2086
https://github.com/open-orchestra/open-orchestra-model-interface/pull/285
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/728
https://github.com/open-orchestra/open-orchestra-elastica-bundle/pull/64
https://github.com/open-orchestra/open-orchestra-media-bundle/pull/245
https://github.com/open-orchestra/open-orchestra-display-bundle/pull/250
https://github.com/open-orchestra/open-orchestra-mongo-libs/pull/69
> Manage version

- ModelBundle/Repository/StatusRepository.php
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/729
https://github.com/open-orchestra/open-orchestra-model-interface/pull/286
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2088
https://github.com/open-orchestra/open-orchestra/pull/1141
> fix workflow list status

- ModelBundle/DataFixtures/MongoDB/DemoContent/Error404DataGenerator.php
- ModelBundle/DataFixtures/MongoDB/DemoContent/Error503DataGenerator.php
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2092
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/730
> update error node

- ModelBundle/DataFixtures/MongoDB/DemoContent/AbstractDataGenerator.php
- ModelBundle/DataFixtures/MongoDB/LoadNodeRootFunctionalDemoData.php
- ModelBundle/Document/Block.php
https://github.com/open-orchestra/open-orchestra-front-bundle/pull/210
https://github.com/open-orchestra/open-orchestra-elastica-bundle/pull/65
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2093
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/731
https://github.com/open-orchestra/open-orchestra-model-interface/pull/287
https://github.com/open-orchestra/open-orchestra-display-bundle/pull/251
> remove block parameter

- ModelBundle/Document/Node.php
- ModelBundle/Repository/NodeRepository.php
https://github.com/open-orchestra/open-orchestra-display-bundle/pull/253
https://github.com/open-orchestra/open-orchestra/pull/1144
https://github.com/open-orchestra/open-orchestra-mongo-libs/pull/70
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/733
https://github.com/open-orchestra/open-orchestra-model-interface/pull/289
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2096
> add use trackable node

- ModelBundle/DataFixtures/MongoDB/LoadDemoSiteData.php
- ModelBundle/DataFixtures/MongoDB/LoadSiteData.php
- ModelBundle/Resources/config/validation/site.yml
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/737
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2118
> fix require main author site

- ModelBundle/Resources/config/validation/site.yml
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2124
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/738
> add constraint site alias count

- ModelBundle/Document/Content.php
- ModelBundle/Document/Node.php
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/740
https://github.com/open-orchestra/open-orchestra-model-interface/pull/291
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2125
> use method init keywords

- ModelBundle/DataFixtures/MongoDB/DemoContent/AbstractDataGenerator.php
- ModelBundle/DataFixtures/MongoDB/DemoContent/AutoPublishDataGenerator.php
- ModelBundle/DataFixtures/MongoDB/DemoContent/CommunityDataGenerator.php
- ModelBundle/DataFixtures/MongoDB/DemoContent/ContactDataGenerator.php
- ModelBundle/DataFixtures/MongoDB/DemoContent/Error404DataGenerator.php
- ModelBundle/DataFixtures/MongoDB/DemoContent/Error503DataGenerator.php
- ModelBundle/DataFixtures/MongoDB/DemoContent/LegalDataGenerator.php
- ModelBundle/DataFixtures/MongoDB/DemoContent/NewsDataGenerator.php
- ModelBundle/DataFixtures/MongoDB/DemoContent/NodeRootFunctionalDataGenerator.php
- ModelBundle/DataFixtures/MongoDB/LoadDeletedSiteNodeData.php
- ModelBundle/DataFixtures/MongoDB/LoadDemoSiteData.php
- ModelBundle/DataFixtures/MongoDB/LoadSiteData.php
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2130
https://github.com/open-orchestra/open-orchestra/pull/1153
https://github.com/open-orchestra/open-orchestra-front-bundle/pull/213
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/741
> update template fixture node

- ModelBundle/Repository/ContentRepository.php
https://github.com/open-orchestra/open-orchestra/pull/1158
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2136
https://github.com/open-orchestra/open-orchestra-model-interface/pull/294
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/745
> add repository method to allow create content in new language

- ModelBundle/Document/Redirection.php
- ModelBundle/Document/Theme.php
- ModelBundle/Document/TrashItem.php
- ModelBundle/Resources/config/listener.yml
https://github.com/open-orchestra/open-orchestra-libs/pull/75
https://github.com/open-orchestra/open-orchestra/pull/1156
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2133
https://github.com/open-orchestra/open-orchestra-base-api-mongo-model-bundle/pull/33
https://github.com/open-orchestra/open-orchestra-mongo-libs/pull/73
https://github.com/open-orchestra/open-orchestra-user-bundle/pull/141
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/742
> Remove annotation search

- ModelBundle/DataFixtures/MongoDB/DemoContent/AbstractDataGenerator.php
- ModelBundle/DataFixtures/MongoDB/LoadStatusData.php
- ModelBundle/DataFixtures/MongoDB/LoadStatusDataFunctional.php
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2139
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/746
> Update status color in fixtures

- ModelBundle/Document/EmbedStatus.php
- ModelBundle/Document/TrashItem.php
- ModelBundle/Repository/ContentRepository.php
- ModelBundle/Repository/NodeRepository.php
- ModelBundle/Repository/TrashItemRepository.php
- ModelBundle/Tests/DependencyInjection/OpenOrchestraModelExtensionTest.php
https://github.com/open-orchestra/open-orchestra/pull/1160
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2144
https://github.com/open-orchestra/open-orchestra-model-interface/pull/295
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/747
https://github.com/open-orchestra/open-orchestra-elastica-bundle/pull/66
> Add trashcan

- ModelBundle/Document/Content.php
https://github.com/open-orchestra/open-orchestra/pull/1164
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/749
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2160
> fix clone content reset date

- ModelBundle/Repository/ContentRepository.php
- ModelBundle/Repository/NodeRepository.php
- ModelBundle/Repository/SiteRepository.php
- ModelBundle/Repository/StatusRepository.php
- ModelBundle/Repository/TrashItemRepository.php
https://github.com/open-orchestra/open-orchestra/pull/1166
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/363
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/751
https://github.com/open-orchestra/open-orchestra-user-bundle/pull/143
https://github.com/open-orchestra/open-orchestra-mongo-libs/pull/74
https://github.com/open-orchestra/open-orchestra-model-interface/pull/297
https://github.com/open-orchestra/open-orchestra-media-bundle/pull/254
https://github.com/open-orchestra/open-orchestra-libs/pull/76
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2165
https://github.com/open-orchestra/open-orchestra-base-api-mongo-model-bundle/pull/34
https://github.com/open-orchestra/open-orchestra-base-api-bundle/pull/119
> remove useless code

- ModelBundle/DataFixtures/MongoDB/LoadNodeRootFunctionalDemoData.php
Media migration
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/362
https://github.com/open-orchestra/open-orchestra-migration-bundle/pull/3
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/750
> Update media fixture

- ModelBundle/Document/Block.php
https://github.com/open-orchestra/open-orchestra-display-bundle/pull/256
https://github.com/open-orchestra/open-orchestra-model-interface/pull/299
https://github.com/open-orchestra/open-orchestra-front-bundle/pull/217
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/755
> add block cache strategy

- ModelBundle/DataFixtures/MongoDB/LoadDemoSiteData.php
- ModelBundle/Document/Site.php
- ModelBundle/Repository/ContentRepository.php
- ModelBundle/Repository/ContentTypeRepository.php
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2180
https://github.com/open-orchestra/open-orchestra-model-interface/pull/300
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/756
> add content type choice on site form

- ModelBundle/Document/Node.php
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2173
https://github.com/open-orchestra/open-orchestra-front-bundle/pull/215
https://github.com/open-orchestra/open-orchestra-model-interface/pull/298
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/754
https://github.com/open-orchestra/open-orchestra-display-bundle/pull/255
> add new property

- ModelBundle/DataFixtures/MongoDB/LoadNodeRootFunctionalDemoData.php
- ModelBundle/Document/Block.php
- ModelBundle/Repository/BlockRepository.php
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/758
https://github.com/open-orchestra/open-orchestra/pull/1173
https://github.com/open-orchestra/open-orchestra-model-interface/pull/302
https://github.com/open-orchestra/open-orchestra-front-bundle/pull/218
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2199
> Add code block

- ModelBundle/Repository/ContentRepository.php
- ModelBundle/Repository/NodeRepository.php
- ModelBundle/Repository/RepositoryTrait/StatusableTrait.php
https://github.com/open-orchestra/open-orchestra/pull/1175
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/759
https://github.com/open-orchestra/open-orchestra-model-interface/pull/303
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2200
> add method to update embedded status

- ModelBundle/Repository/SiteRepository.php
https://github.com/open-orchestra/open-orchestra-media-bundle/pull/256
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/757
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/367
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2189
https://github.com/open-orchestra/open-orchestra/pull/1171
https://github.com/open-orchestra/open-orchestra-model-interface/pull/301
> add media share site

- ModelBundle/Repository/NodeRepository.php
https://github.com/open-orchestra/open-orchestra-model-interface/pull/304
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/760
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2207
https://github.com/open-orchestra/open-orchestra/pull/1178
> remove unused method node repo

- ModelBundle/Repository/NodeRepository.php
https://github.com/open-orchestra/open-orchestra-model-interface/pull/305
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/761
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2229
https://github.com/open-orchestra/open-orchestra/pull/1189
> add tree node on new site alias language

- ModelBundle/Document/ContentType.php
- ModelBundle/Repository/NodeRepository.php
- ModelBundle/Tests/Validator/Constraints/UniqueContentTypeIdValidatorTest.php
- ModelBundle/Validator/Constraints/UniqueContentTypeIdValidator.php
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2235
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/764
https://github.com/open-orchestra/open-orchestra/pull/1192
> Fix first edition of content type

- ModelBundle/Repository/ContentRepository.php
- ModelBundle/Repository/NodeRepository.php
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2249
https://github.com/open-orchestra/open-orchestra-media-bundle/pull/260
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/382
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/766
https://github.com/open-orchestra/open-orchestra-model-interface/pull/306
> Add commande hard delete site

- ModelBundle/Resources/config/validation/site.yml
https://github.com/open-orchestra/open-orchestra-front-bundle/pull/222
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2257
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/767
> remove require meta author

- ModelBundle/Repository/NodeRepository.php
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2278
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/770
https://github.com/open-orchestra/open-orchestra-model-interface/pull/310
https://github.com/open-orchestra/open-orchestra/pull/1205
> restore node under father

- ModelBundle/Repository/BlockRepository.php
https://github.com/open-orchestra/open-orchestra-front-bundle/pull/223
https://github.com/open-orchestra/open-orchestra-model-interface/pull/308
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/768
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2270
> add code block siteId

- ModelBundle/DataFixtures/MongoDB/LoadContentTypeData.php
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2286
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/771
> Make content type Customer fixture non workflowable

- ModelBundle/Repository/NodeRepository.php
- ModelBundle/Repository/RouteDocumentRepository.php
https://github.com/open-orchestra/open-orchestra/pull/1209
https://github.com/open-orchestra/open-orchestra-model-interface/pull/311
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/772
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2292
> optimize create/delete route document

- ModelBundle/EventListener/GenerateIdListener.php
https://github.com/open-orchestra/open-orchestra/pull/1217
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/400
https://github.com/open-orchestra/open-orchestra-media-bundle/pull/267
https://github.com/open-orchestra/open-orchestra-migration-bundle/pull/20
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/774
> GenerateIdListener works now on a source of type array

- ModelBundle/Repository/RepositoryTrait/AutoPublishableTrait.php
- ModelBundle/Repository/StatusRepository.php
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2317
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/775
https://github.com/open-orchestra/open-orchestra/pull/1219
> fix out of worklow find

- ModelBundle/DataFixtures/MongoDB/LoadDemoSiteData.php
https://github.com/open-orchestra/open-orchestra-media-bundle/pull/269
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/409
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/776
https://github.com/open-orchestra/open-orchestra-elastica-admin-bundle/pull/2
> remove load media by keywords

- ModelBundle/DependencyInjection/OpenOrchestraModelExtension.php
- ModelBundle/HealthCheck/MongoDbConnectionTest.php
- ModelBundle/Resources/config/health_check.yml
- ModelBundle/Resources/config/helper.yml
- ModelBundle/Tests/HealthCheck/MongoDbConnexionTestTest.php
https://github.com/open-orchestra/open-orchestra-base-bundle/pull/127
https://github.com/open-orchestra/open-orchestra-front-bundle/pull/228
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/780
https://github.com/open-orchestra/open-orchestra-elastica-bundle/pull/77
> add health check

- ModelBundle/Repository/NodeRepository.php
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2346
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/420
https://github.com/open-orchestra/open-orchestra-media-bundle/pull/273
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/781
https://github.com/open-orchestra/open-orchestra-model-interface/pull/315
https://github.com/open-orchestra/open-orchestra/pull/1233
> suppress recursive path

- ModelBundle/Document/Area.php
https://github.com/open-orchestra/open-orchestra-model-interface/pull/316
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/782
> fix block in area at first position
